{
 "title": "Fabric-X-Committer Performance Dashboard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "sig_verifier_instance",
    "label": "Sig Verifier Servers",
    "query": {
     "query": "sc_component_type{component=\"sigverifier\"}"
    }
   },
   {
    "name": "coordinator_instance",
    "label": "Coordinator Servers",
    "query": {
     "query": "sc_component_type{component=\"coordinator\"}"
    }
   },
   {
    "name": "shards_service_instance",
    "label": "Shard Servers",
    "query": {
     "query": "sc_component_type{component=\"shards-service\"}"
    }
   },
   {
    "name": "generator_instance",
    "label": "Generator Servers",
    "query": {
     "query": "sc_component_type{component=\"generator\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(loadgen_transaction_received_total[10s])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(loadgen_transaction_sent_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(loadgen_valid_transaction_latency_seconds_bucket[$__interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(loadgen_invalid_transaction_latency_seconds_bucket[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Relay Input Block Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sidecar_relay_input_block_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Output Block Queue Size -- Input to Block Store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sidecar_relay_output_committed_block_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Waiting Transactions Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sidecar_relay_waiting_transactions_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Block Mapping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(rate(sidecar_relay_block_mapping_seconds_sum[5s])) / rate(sidecar_relay_block_mapping_seconds_count[5s]) * 1000 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Mapped Block Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "(rate(sidecar_relay_mapped_block_processing_seconds_sum[5s])) / rate(sidecar_relay_mapped_block_processing_seconds_count[5s]) * 1000 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Tx Status Batch Processing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "(rate(sidecar_relay_transaction_status_batch_processing_seconds_sum[5s])) / rate(sidecar_relay_transaction_status_batch_processing_seconds_count[5s]) * 1000 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ledger Append Block Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "(rate(sidecar_ledger_append_block_seconds_sum[5s])) / rate(sidecar_ledger_append_block_seconds_count[5s]) * 1000 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ledger Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    { "expr": "sidecar_ledger_block_height", "legendFormat": "__auto" }
   ]
  },
  { "title": "Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Transaction Received Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_grpc_received_transaction_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Valid and Invalid Txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coordinator_grpc_committed_transaction_total[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Valid Txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(coordinator_grpc_committed_transaction_total{status=\"COMMITTED\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Invalid Txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(coordinator_grpc_committed_transaction_total{status!=\"COMMITTED\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Graph Manager Input Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "coordinator_local_dependency_graph_input_tx_batch_queue_size",
     "legendFormat": "Local Dependency Graph Input Queue Size"
    },
    {
     "expr": "coordinator_global_dependency_graph_input_tx_batch_queue_size",
     "legendFormat": "Global Dependency Graph Input Queue Size"
    }
   ]
  },
  {
   "title": "SVM Input Queue Sizes (a.k.a. Graph Output Queue Size)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "coordinator_sigverifier_input_tx_batch_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_sigverifier_output_valid_block_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_sigverifier_output_invalid_block_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VCM Output Validated Queue Size -- Input to Dependency Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "coordinator_vcservice_output_validated_tx_batch_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVM Input Queue Sizes (a.k.a. Graph Output Queue Size)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "coordinator_sigverifier_input_tx_batch_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_sigverifier_output_valid_block_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_sigverifier_output_invalid_block_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VCM Output Validated Queue Size -- Response to Sidecar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "coordinator_vcservice_output_tx_status_batch_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Global Dependency Graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_global_dependency_graph_tx_processed_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Signature Verifier)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_sigverifier_transaction_processed_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Local Dependency Graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_local_dependency_graph_tx_processed_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Global Dependency Graph - Post Validation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_global_dependency_graph_validated_tx_processed_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (VC Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_vcservice_transaction_processed_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVM Retried Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_sigverifier_retired_transaction_total[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VCM Retried Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_vcservice_retired_transaction_total[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Graph Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "targets": [
    {
     "expr": "coordinator_global_dependency_graph_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Dependency Graph -- ConstructDependencyGraph()",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "(rate(coordinator_global_dependency_graph_construction_seconds_sum[10s])) / rate(coordinator_global_dependency_graph_construction_seconds_count[10s]) * 1000",
     "legendFormat": "ConstructDependencyGraph"
    },
    {
     "expr": "rate(coordinator_global_dependency_graph_constructor_wait_for_lock_seconds_sum[10s]) * 1000 / rate(coordinator_global_dependency_graph_constructor_wait_for_lock_seconds_count[10s])",
     "legendFormat": "Waiting For Lock"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_add_tx_batch_to_graph_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_add_tx_batch_to_graph_seconds_count[10s])",
     "legendFormat": "Add Tx Batch To Graph"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_update_dependency_detector_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_update_dependency_detector_seconds_count[10s])",
     "legendFormat": "Add Tx Batch to Dependency Detector"
    }
   ]
  },
  {
   "title": "Global Dependency Graph - ProcessValidatedTransactions()",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "(rate(coordinator_global_dependency_graph_validated_tx_batch_processing_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_validated_tx_batch_processing_seconds_count[10s])",
     "legendFormat": "ProcessValidatedTx"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_validated_tx_batch_processor_wait_for_lock_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_validated_tx_batch_processor_wait_for_lock_seconds_count[10s])",
     "legendFormat": "Waiting For Lock"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_remove_dependents_of_validated_tx_batch_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_remove_dependents_of_validated_tx_batch_seconds_count[10s])",
     "legendFormat": "Remove Dependents and Find Freed Txs"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_add_freed_tx_batch_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_add_freed_tx_batch_seconds_count[10s])",
     "legendFormat": "Add Freed Transactions"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\", job=\"coordinators\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{ job=\"coordinators\" }",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"coordinators\"} - node_memory_MemFree_bytes{job=\"coordinators\"} - (node_memory_Cached_bytes{job=\"coordinators\"} + node_memory_Buffers_bytes{job=\"coordinators\"} + node_memory_SReclaimable_bytes{job=\"coordinators\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{ job=\"coordinators\" }[$__interval])) * 8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{job=\"coordinators\"}[$__interval])) * 8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$__interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  { "title": "VCService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Total Throughput (RPS*)",
   "type": "timeseries",
   "description": "If the TX consists of multiple SNs (e.g. 4), it will be most probably split into different shards (e.g. 2 shards will get each 1 SN and 1 shard will get 2). It will count as one TX for each shard and that will give a false total of 3 TXs instead of 1.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(vcservice_committed_transaction_total[$__interval]))",
     "legendFormat": "In ({{instance}})"
    }
   ]
  },
  {
   "title": "Transaction Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "rate(vcservice_grpc_received_transaction_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "targets": [
    {
     "expr": "rate(vcservice_grpc_processed_transaction_total[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Preparer Input Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "targets": [
    {
     "expr": "vcservice_preparer_input_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Input Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "vcservice_validator_input_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committer Input Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 150 },
   "targets": [
    {
     "expr": "vcservice_committer_input_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committer Output Queue Size -- Response to Coordinator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 150 },
   "targets": [
    {
     "expr": "vcservice_txstatus_output_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Preparer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_preparer_tx_batch_latency_seconds_sum[5s]) * 1000)/rate(vcservice_preparer_tx_batch_latency_seconds_count[5s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_validator_tx_batch_latency_seconds_sum[5s]) * 1000)/rate(vcservice_validator_tx_batch_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_committer_tx_batch_latency_seconds_sum[5s]) * 1000)/rate(vcservice_committer_tx_batch_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Validation Latency (per batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_validation_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_validation_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Query Version Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_query_version_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_query_version_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Commit Latency (per batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_commit_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_commit_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Status Commit Latency  (per batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_commit_txs_status_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_commit_txs_status_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Update Latency  (per batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_commit_update_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_commit_update_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Insert New Keys With Value Commit Latency  (per batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_commit_insert_new_key_with_value_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_commit_insert_new_key_with_value_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Insert New Keys Without Value Commit Latency  (per batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(vcservice_database_tx_batch_commit_insert_new_key_without_value_latency_seconds_sum[5s]) * 1000)/rate(vcservice_database_tx_batch_commit_insert_new_key_without_value_latency_seconds_count[5s]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$shards_service_instance:.+\"}",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$shards_service_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$shards_service_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$shards_service_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$shards_service_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$shards_service_instance:.+\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$shards_service_instance:.+\"} [$__interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(instance) (sum by(instance, cpu) (rate(node_cpu_seconds_total{\"$shards_service_instance\"=~\"$shards_service_instance\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "targets": [
    {
     "expr": "sc_go_routines{component=\"shards-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$shards_service_instance:.+\"}[$__interval]))*8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$shards_service_instance:.+\"}[$__interval]))*8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "Channel-Buffer Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "targets": [
    {
     "expr": "sc_channel_length{component=\"shards-service\"}",
     "legendFormat": "{{sub_component}} > {{channel}}"
    }
   ]
  },
  {
   "title": "Shard DB read/write 99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(sc_shard_db_read_latency_bucket[$__interval]))",
     "legendFormat": "{{instance}} - Read"
    },
    {
     "expr": "histogram_quantile(0.95, rate(sc_shard_db_write_latency_bucket[$__interval])) * -1",
     "legendFormat": "{{instance}} - Write"
    }
   ]
  },
  {
   "title": "Shard sizes (committed Serial numbers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sc_component_throughput{component=\"shards-service\", direction=\"out\"}",
     "legendFormat": "Shard {{sub_component}}"
    }
   ]
  },
  {
   "title": "Data structure sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
   "targets": [
    {
     "expr": "sc_data_structure_size{component=\"shards-service\"}",
     "legendFormat": "{{sub_component}} > {{prop}}"
    }
   ]
  },
  { "title": "Sig Verifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 229 } },
  {
   "title": "Total Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(sc_component_throughput{instance=~\"$sig_verifier_instance:.+\",sub_component=\"verifier_server\",direction=\"in\"}[$__interval]))",
     "legendFormat": "In ({{instance}})"
    },
    {
     "expr": "sum by (instance) (-1 * rate(sc_component_throughput{instance=~\"$sig_verifier_instance:.+\",sub_component=\"verifier_server\",direction=\"out\"}[$__interval]))",
     "legendFormat": "Out ({{instance}})"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "gauge",
   "description": "How many clients have an open stream to the server",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sc_active_streams", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sc_sigverifier_latency_bucket[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\"}[$__interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$sig_verifier_instance:.+\"}",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$sig_verifier_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$sig_verifier_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$sig_verifier_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$sig_verifier_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$sig_verifier_instance:.+\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 255 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$sig_verifier_instance:.+\"}[$__interval]))*8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$sig_verifier_instance:.+\"}[$__interval]))*8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 255 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$sig_verifier_instance:.+\"} [$__interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Channel-Buffer Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 262 },
   "targets": [
    {
     "expr": "sc_channel_length{component=\"sigverifier\"}",
     "legendFormat": "{{sub_component}} > {{channel}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 262 },
   "targets": [
    {
     "expr": "sc_go_routines{component=\"sigverifier\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Detailed Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"in\"}[$__interval])",
     "legendFormat": "In {{sub_component}} ({{instance}})"
    },
    {
     "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"out\"}[30s]) * -1",
     "legendFormat": "Out {{sub_component}} ({{instance}})"
    }
   ]
  }
 ]
}