#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# This inventory runs an Hyperledger Fabric-X Committer with a loadgen that acts also as mocking orderer.

# To run this inventory, follow the steps:
# 1. make generate-crypto build-bins && make fabric_x_committer transfer && make load_generators transfer && make monitoring transfer

# To start:
# make fabric_x_committer start && make load_generators start && make monitoring start

# To stop the network:
# make teardown

all:
  vars:
    # =========================
    # Organizations
    # =========================
    container_client: docker
    committer_git_uri: "https://github.com/cendhu/fabric-x-committer.git"
    committer_git_commit: "bench-feb-2026"
    loadgen_git_uri: "https://github.com/cendhu/fabric-x-committer.git"
    loadgen_git_commit: "bench-feb-2026"
    organizations:
      orderer_org_1: &OrdererOrg1
        name: OrdererOrg1
        domain: ordererorg1.example.com
      org1: &Org1
        name: Org1
        domain: org1.example.com
  children:
    # =========================
    # Network (HLFX)
    # =========================
    network:
      children:
        # =========================
        # Hyperledger Fabric-X
        # =========================
        fabric_x:
          children:
            # =========================
            # HLFX Orderers
            # =========================
            fabric_x_orderers:
              children:
                # fake orderer replicating the same endpoint as the mock orderer
                # set as many assemblers as ports in loadgen_mock_orderer_ports
                # assign each assembler to the same host and port of the loadgen
                mock_orderer:
                  vars:
                    organization:
                      <<: *OrdererOrg1
                      role: orderer
                    orderer_group: 1
                  hosts:
                    mock-orderer-assembler-1:
                      ansible_host: "{{ host_machine_23 }}"
                      orderer_component_type: assembler
                      orderer_rpc_port: 8001

            # =========================
            # HLFX Committer
            # =========================
            fabric_x_committer:
              vars:
                committer_use_bin: true
                committer_build_bin: true
                committer_rpc_port: 8004
                prometheus_exporter_port: 8002
                organization:
                  <<: *Org1
                  role: peer
              hosts:
                committer-sidecar:
                  committer_component_type: sidecar
                  committer_remote_deploy_dir: "/data/committer-aws-deployment"
                  committer_remote_node_dir: "/data/committer-aws-deployment/committer-sidecar"
                  committer_remote_config_dir: "/data/committer-aws-deployment/committer-sidecar/config"
                  committer_sidecar_sync_interval: 100
                  ansible_host: "{{ host_machine_22 }}"
                committer-coordinator:
                  committer_component_type: coordinator
                  ansible_host: "{{ host_machine_24 }}"
              children:
                committer_validators:
                  vars:
                    committer_component_type: validator
                    prometheus_exporter_port: 8009
                    yugabyte_cluster_ref_id: 1
                    committer_resource_limits_max_workers_for_preparer: 20
                    committer_resource_limits_max_workers_for_validator: 20
                    committer_resource_limits_max_workers_for_committer: 20
                  hosts:
                    committer-validator-1:
                      ansible_host: "{{ host_machine_12 }}"
                    committer-validator-2:
                      ansible_host: "{{ host_machine_13 }}"
                    committer-validator-3:
                      ansible_host: "{{ host_machine_14 }}"
                    committer-validator-4:
                      ansible_host: "{{ host_machine_15 }}"
                committer_verifiers:
                  vars:
                    committer_component_type: verifier
                  hosts:
                    committer-verifier-1:
                      ansible_host: "{{ host_machine_4 }}"
                    committer-verifier-2:
                      ansible_host: "{{ host_machine_5 }}"
                    committer-verifier-3:
                      ansible_host: "{{ host_machine_6 }}"
                    committer-verifier-4:
                      ansible_host: "{{ host_machine_7 }}"
                committer_dbs:
                  vars:
                    yugabyte_user: yugabyte
                    yugabyte_password: yugabyte
                    yugabyte_db: yugabyte
                    yugabyte_cluster_id: 1
                  children:
                    yb_masters:
                      vars:
                        yugabyte_component_type: master
                        yugabyte_master_rpc_bind_port: 8003
                        yugabyte_master_webserver_port: 8004
                      hosts:
                        yugabytedb-master-1:
                          ansible_host: "{{ host_machine_9 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-master-2:
                          ansible_host: "{{ host_machine_10 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-master-3:
                          ansible_host: "{{ host_machine_11 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                    yb_tablets:
                      vars:
                        yugabyte_component_type: tablet
                        yugabyte_tablet_pgsql_bind_port: 8001
                        yugabyte_tablet_rpc_bind_port: 8002
                        yugabyte_tablet_webserver_port: 8003
                        yugabyte_tablet_redis_web_port: 8004
                        yugabyte_tablet_cql_web_port: 8005
                        yugabyte_tablet_pgsql_web_port: 8006
                        yugabyte_tablet_cql_bind_port: 8007
                        yugabyte_tablet_redis_rpc_port: 8008
                      hosts:
                        yugabytedb-tablet-1:
                          ansible_host: "{{ host_machine_12 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-2:
                          ansible_host: "{{ host_machine_13 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-3:
                          ansible_host: "{{ host_machine_14 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-4:
                          ansible_host: "{{ host_machine_15 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-5:
                          ansible_host: "{{ host_machine_16 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-6:
                          ansible_host: "{{ host_machine_17 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-7:
                          ansible_host: "{{ host_machine_18 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-8:
                          ansible_host: "{{ host_machine_19 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-9:
                          ansible_host: "{{ host_machine_20 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"
                        yugabytedb-tablet-10:
                          ansible_host: "{{ host_machine_21 }}"
                          remote_deploy_dir: "/data/committer-aws-deployment"

    # =========================
    # HLFX LoadGens
    # =========================
    load_generators:
      vars:
        organization:
          <<: *Org1
          role: peer
          users:
            - name: orderer-loadgen
              namespace: 0
        loadgen_type: sidecar-client
        loadgen_mock_orderer_ports:
          - 8001
        loadgen_web_port: 8002
        prometheus_exporter_port: 8003
        loadgen_build_bin: true
        loadgen_use_bin: true
        loadgen_limit_rate: 450000
        loadgen_block_size: 500
        loadgen_workers: 128
        loadgen_stream_batches: 500
        loadgen_stream_buffers_size: 100
        loadgen_read_write_tx_keys: 2

      hosts:
        orderer-loadgen-1:
          ansible_host: "{{ host_machine_23 }}"
          loadgen_tx_seed: 12345

    # =========================
    # Monitoring Infra
    # =========================
    monitoring:
      vars:
        ansible_host: "{{ host_machine_8 }}"
      children:
        node_exporters:
          vars:
            node_exporter_port: 8010
          hosts:
            node-ansible:
              ansible_host: "{{ host_machine_1 }}"
            node-loadgen:
              ansible_host: "{{ host_machine_2 }}"
            node-coordinator:
              ansible_host: "{{ host_machine_24 }}"
            node-validator-1:
              ansible_host: "{{ host_machine_12 }}"
            node-validator-2:
              ansible_host: "{{ host_machine_13 }}"
            node-validator-3:
              ansible_host: "{{ host_machine_14 }}"
            node-validator-4:
              ansible_host: "{{ host_machine_15 }}"
            node-verifier-1:
              ansible_host: "{{ host_machine_4 }}"
            node-verifier-2:
              ansible_host: "{{ host_machine_5 }}"
            node-verifier-3:
              ansible_host: "{{ host_machine_6 }}"
            node-verifier-4:
              ansible_host: "{{ host_machine_7 }}"
            node-master-1:
              ansible_host: "{{ host_machine_9 }}"
            node-master-2:
              ansible_host: "{{ host_machine_10 }}"
            node-master-3:
              ansible_host: "{{ host_machine_11 }}"
            node-tablet-1:
              ansible_host: "{{ host_machine_12 }}"
            node-tablet-2:
              ansible_host: "{{ host_machine_13 }}"
            node-tablet-3:
              ansible_host: "{{ host_machine_14 }}"
            node-tablet-4:
              ansible_host: "{{ host_machine_15 }}"
            node-tablet-5:
              ansible_host: "{{ host_machine_16 }}"
            node-tablet-6:
              ansible_host: "{{ host_machine_17 }}"
            node-tablet-7:
              ansible_host: "{{ host_machine_18 }}"
            node-tablet-8:
              ansible_host: "{{ host_machine_19 }}"
            node-tablet-9:
              ansible_host: "{{ host_machine_20 }}"
            node-tablet-10:
              ansible_host: "{{ host_machine_21 }}"
            node-sidecar:
              ansible_host: "{{ host_machine_22 }}"
            node-loadgen-2:
              ansible_host: "{{ host_machine_23 }}"
      hosts:
        prometheus:
          prometheus_port: 8005
        grafana:
          grafana_username: admin
          grafana_password: adminPWD
          grafana_web_port: 8006
          prometheus_host: prometheus
